version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app # Mount the project directory
      - /usr/src/app/node_modules # Keep node_modules from being overridden
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/testingDexieSync6
    command: npx nodemon --watch src -e ts,js --exec 'ts-node src/main.js'

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo-data:
